name: 🚀 Backend deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    uses: dyne/workflows/.github/workflows/pocketbase-deploy.yml@main
    secrets: inherit
    with:
      project_name: broken
      fqnd: "http://159.69.20.15:8091"
